# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Either Walkers' and Vehicles' Trajectory
#' 
#' This function uses (new) Agent Class. Not yet fully tested
#' 
#' @export
run <- function(time, para, pos, goal, so, ao, ss, sa, obstacles, cd) {
    .Call('_commotions_run', PACKAGE = 'commotions', time, para, pos, goal, so, ao, ss, sa, obstacles, cd)
}

#' Simulate P2P Trajectory
#' 
#' This function uses Simulation and Kinematics Classes
#' 
#' @export
test_P2P <- function(time, para, pos, goal, so, ao, ss, sa, obstacles, cd, sr, wall) {
    .Call('_commotions_test_P2P', PACKAGE = 'commotions', time, para, pos, goal, so, ao, ss, sa, obstacles, cd, sr, wall)
}

#' Simulate V2V Trajectory 
#' 
#' This function uses Simulation and Kinematics Classes; one or two agents
#' 
#' @export
test_V2V <- function(time, para, pos, goal, so, ao, ss, sa, obstacles, cd, sr) {
    .Call('_commotions_test_V2V', PACKAGE = 'commotions', time, para, pos, goal, so, ao, ss, sa, obstacles, cd, sr)
}

#' Simulate P2V Trajectory 
#' 
#' This function uses Simulation and Kinematics Classes
#' 
#' @export
test_P2V <- function(time, para, pos, goal, so, ao, ss, sa, obstacles, cd, sr) {
    .Call('_commotions_test_P2V', PACKAGE = 'commotions', time, para, pos, goal, so, ao, ss, sa, obstacles, cd, sr)
}

#' @export
test_SC_P2V_tmp <- function(time, para, initial_position, destination, action0, action1, initial_speed, initial_angle, collision_distance, conflict_point, optional_assumptions, debug) {
    .Call('_commotions_test_SC_P2V_tmp', PACKAGE = 'commotions', time, para, initial_position, destination, action0, action1, initial_speed, initial_angle, collision_distance, conflict_point, optional_assumptions, debug)
}

#' @export
test_regspace <- function(st, dt, et) {
    .Call('_commotions_test_regspace', PACKAGE = 'commotions', st, dt, et)
}

#' @export
test_armaregspace <- function(st, dt, et) {
    .Call('_commotions_test_armaregspace', PACKAGE = 'commotions', st, dt, et)
}

#' @export
test_Kinematics_old <- function(pos, goal, speed, angle, soption, yoption) {
    invisible(.Call('_commotions_test_Kinematics_old', PACKAGE = 'commotions', pos, goal, speed, angle, soption, yoption))
}

#' @export
test_Kinematics <- function(para, pos, goal, so, ao, ss, sa, cd, sr) {
    invisible(.Call('_commotions_test_Kinematics', PACKAGE = 'commotions', para, pos, goal, so, ao, ss, sa, cd, sr))
}

#' @export
test_Parameters <- function(x) {
    invisible(.Call('_commotions_test_Parameters', PACKAGE = 'commotions', x))
}

#' @export
test_KCollide <- function(pos, goal, init_speed, init_angle, x, y, speed, angle, obs_x, obs_y) {
    .Call('_commotions_test_KCollide', PACKAGE = 'commotions', pos, goal, init_speed, init_angle, x, y, speed, angle, obs_x, obs_y)
}

#' @export
test_Simulation <- function(ts) {
    invisible(.Call('_commotions_test_Simulation', PACKAGE = 'commotions', ts))
}

#' @export
test_Initialize <- function(ts, pos, goal, speeds, angles) {
    invisible(.Call('_commotions_test_Initialize', PACKAGE = 'commotions', ts, pos, goal, speeds, angles))
}

#' @export
test_pAgent <- function(s0, s1) {
    .Call('_commotions_test_pAgent', PACKAGE = 'commotions', s0, s1)
}

#' @export
test_List <- function(x) {
    .Call('_commotions_test_List', PACKAGE = 'commotions', x)
}

#' @export
test_find <- function(a) {
    .Call('_commotions_test_find', PACKAGE = 'commotions', a)
}

#' @export
test_switch <- function(a) {
    .Call('_commotions_test_switch', PACKAGE = 'commotions', a)
}

#' @export
test_arma_find <- function(cd, proj_signed_dist_to_CP) {
    .Call('_commotions_test_arma_find', PACKAGE = 'commotions', cd, proj_signed_dist_to_CP)
}

#' Is Two Segment Parallel?
#' 
#' Test whether two segments run parallel or across each other.
#' 
#' @param segment0 the four coordinates of the first segment, c(x0, y0, x1, y1)
#' @param segment1 the four coordinates of the second segment, c(x0, y0, x1, y1)  
#' 
#' @return Boolean TRUE or FALSE
#' @references https://math.stackexchange.com/questions/1342435/how-to-determine-if-2-line-segments-cross
#' @examples 
#' pos <- matrix(c(-5, -5, -5, 5), ncol=2)
#' segment0 <- c(pos[1,], pos[2,])
#' wall <- c(-5, 0, -2.5, 0)
#' is_cross(segment0, wall)
#' @export
is_cross <- function(segment0, segment1) {
    .Call('_commotions_is_cross', PACKAGE = 'commotions', segment0, segment1)
}

#' get_intersection_of_lines
#' 
#' get_intersection_of_lines
#'
#' @param line1_pointA self_pos
#' @param line1_pointB self_goal
#' @param line2_pointA other_pos
#' @param line2_pointB other_goal
#' 
#' @return a vector
#' @examples
#' pos  <- matrix(c(0, -5, 40, 0), ncol=2); pos
#' goal <- matrix(c(0, 5, -50, 0), ncol=2); goal
#' self_pos <- pos[,1]
#' self_goal <- goal[,1] 
#' other_pos <- pos[,2]
#' other_goal <- goal[,2] 
#' res <- get_intersection_of_lines(self_pos, self_goal, other_pos, other_goal)
#' ## [1] 0 0
#' @export
get_intersection_of_lines <- function(line1_pointA, line1_pointB, line2_pointA, line2_pointB) {
    .Call('_commotions_get_intersection_of_lines', PACKAGE = 'commotions', line1_pointA, line1_pointB, line2_pointA, line2_pointB)
}

